apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rasppi516
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  nodeSelector: |
    kubernetes.io/hostname: rasppi516
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
