---
apiVersion: v1
kind: LimitRange
metadata:
  name: media-defaults
  namespace: media
spec:
  limits:
  - type: Container
    # Máximo permitido por contenedor
    max:
      cpu: "500m"
      memory: "1Gi"
    # Requests mínimos por defecto (para que el Pod arranque con lo mínimo)
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
    # Límites por defecto (tope si no especificas resources)
    default:
      cpu: "500m"
      memory: "1Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-quota
  namespace: media
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "6Gi"
    limits.cpu: "4"
    limits.memory: "12Gi"
